_base:
  - configs/eeg_power_distribution/base.yaml
  - configs/eeg_power_distribution/model-small.yaml
data:
  common:
    batch_size: 32
    num_workers: 32
task:
  optimizer:
    _name: torch.optim.Adam
    lr: 0.0001

PATIENCE: 10
