project: sleep-staging
job_type: bcg_2k_test
data:
  _name: wuji_dl.data.DefaultDataModule
  common:
    _name: data.spo2.Spo2Dataset
    index: index/spo2/bcg_spo2.csv
    max_tokens: 1535
    batch_size: 16
    num_workers: 16
  test:
    split: test
task:
  _name: tasks.spo2.Spo2Task
  test_group: bcg_2k_test
callbacks:
  - _name: lightning.pytorch.callbacks.RichProgressBar
    leave: True
