_base:
  - configs/spo2/base.yaml
  - configs/spo2/model-small.yaml
data:
  common:
    batch_size: 64
    num_workers: 32
task:
  optimizer:
    _name: torch.optim.AdamW
    lr: 0.0010889928039348124

PATIENCE: 10
