_base:
  - configs/spo2/base.yaml
  - configs/spo2/model-small.yaml
data:
  common:
    batch_size: 64
    num_workers: 32
task:
  optimizer:
    _name: torch.optim.AdamW
    lr: 0.0008
  criterion:
    _name: losses.wasserstein_pearson_loss.WassersteinPearsonLoss
    pearson_weight: 0.1

PATIENCE: 10
