_base:
  - configs/diagnosis/base.yaml
project: rbd-diagnosis
data:
  common:
    index: index/diagnosis/ruijin_477.csv
    label: rbd
    max_tokens: 480
    stride_tokens: 480
    batch_size: 64
    num_workers: 64
task:
  results_dir: results/rbd/ruijin_477_test
trainer:
  precision: 16-mixed

PATIENCE: 10
