_base:
  - configs/diagnosis/base.yaml
project: drink
data:
  common:
    index: index/diagnosis/shanghai_7988.csv
    label: drink
    max_tokens: 1535
    batch_size: 16
    num_workers: 16
task:
  model:
    _name: models.diagnosis.DiagnosisNet
    pretrain_task: tasks.sleep_staging.SleepStagingTask
    pretrained: pretrained/sleep_staging_exp1a-42.ckpt
  optimizer:
    _name: torch.optim.Adam
    lr: 1.e-4

PATIENCE: 10
